### ISSUE TITLE
gradlew check fail on :test

### ISSUE THREAD

**Issue by tdicken73** [openvenues/jpostal#1]
I followed the steps of installing libpostal and followed it with installing jpostal. Libpostal works via command line and the jpostal built successfully but the test :test failed when running "./gradlew check" per the readme.md. Below is the following output to the console and the log file is attached.

:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> Process 'Gradle Test Executor 1' finished with non-zero exit value 134

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
[hs_err_pid80052.log.zip](https://github.com/openvenues/jpostal/files/249384/hs_err_pid80052.log.zip)

**Comment by thatdatabaseguy** [comment]
Hm, so I develop on a similar version of OSX with Java 8 and couldn't reproduce the issue here.

From the Native Frames section of the log, it looks like one of the on-disk files from libpostal failed to load. You mentioned libpostal works from the command-line. Did you run the ```address_parser``` program from the libpostal C checkout, and if not, does that work on the command-line?

If you run ```du -h``` on whatever datadir you used when configuring libpostal (default would be /usr/local/share/libpostal), it should read 2.2G. If not, something didn't download correctly and it's best to nuke the datadir and re-run ```make```.

Also, is there enough free memory? The log seems to say that there's 700M free (wasn't clear if that was JVM memory or OS), whereas libpostal would need around 2G (OS memory) total. That still might not cause a malloc fail because of virtual memory, but might want to try wth > 2G free just to rule it out.

**Comment by tdicken73** [comment]
Thanks the looking thru it, my ./libpostal command works but address_parser errors out to Segmentation fault:11. 
![addressparserresult](https://cloud.githubusercontent.com/assets/6421218/15032143/b7991306-1223-11e6-9a11-c6e7dd12a883.png)
When I attempt to run thru the nosetests in the pypostal library, the tests also fail with the same segmentation fault.![pythonsegmentationfault](https://cloud.githubusercontent.com/assets/6421218/15032360/a67b6de2-1225-11e6-82a0-0421c020b206.png)

I believe I am missing some data (data folder "libpostal" was only 1.5gb) but have make'd my libpostal multiple times. 
![datasize](https://cloud.githubusercontent.com/assets/6421218/15032156/cdd67ee2-1223-11e6-9c26-d6fa7e7e20e8.png)

I get a decompression failed issues when running make within libpostal.
![decompressionfailed2](https://cloud.githubusercontent.com/assets/6421218/15032303/0ee63aa2-1225-11e6-9afc-9033d85e2b67.png)
Any help is appreciated!

**Comment by thatdatabaseguy** [comment]
Thanks for the detailed report. That definitely seems like a half-downloaded file. I've just added ```set -e``` to the data download script so at least make will fail if everything doesn't download correctly.

It seems like the disk/partition might be full (so it only downloads part of the tarball and can't decompress it). Do you know whether there's enough space available?

**Comment by tdicken73** [comment]
Thanks for pushing that update, I've pulled it down and rerun `make` but am getting a `x geodb/geodb.spi: gzip decompression failed`. I don't believe it's a storage issue as I'm running this on a newly imaged machine with 1TB Flash Storage, 940GB free.  Here's the specific output when downloading the  geodb data.
![geodb error](https://cloud.githubusercontent.com/assets/6421218/15116210/03431084-15c8-11e6-8b66-f8339a5de900.png)
After this, it now exits the `make` installation. I am able to get libpostal working thru the pypostal plugin but not the jpostal plugin. Would this issue have any effects on that?

**Comment by thatdatabaseguy** [comment]
Hm pypostal shouldn't be working either if geodb is not download (```from postal.parser import parse_address``` should fail but ```from postal.expand import expand_address``` will work). The language bindings are independent of each other and can be installed side-by-side without issues.

Can you try downloading the geodb.tar.gz file (https://s3.amazonaws.com/libpostal/geodb.tar.gz)  to that same directory on the command-line and decompressing it with ```tar -xvzf```? From the log it appears that getting the installation working is contingent on getting that command to work.

Also, is the drive partitioned or anything? Try running ```df -h /Users/dickent/Development/open-source/libpostal/data/libpostal```. Maybe there's space on the drive itself but not on that partition? Not to hammer the point, it just really sounds like a storage issue to me.

**Comment by tdicken73** [comment]
I blew away my original directory and reinstalled libpostal and it seems to
have fixed the issue, both jpostal ./gradlew check is working as well as
nosetests in pypostal. Thanks for your help

**Comment by thatdatabaseguy** [comment]
That is odd. Usually a re-install has ended up being the solution in similar issues. If you happen to encounter this again in the future or find a way to reproduce it, let me know. Glad it's working!
