### ISSUE TITLE
cannot find libpostal

### ISSUE THREAD

**Issue by edi-bice** [openvenues/jpostal#11]
Whether by default in /usr/local/lib or even in /usr/lib and always ldconfig -p | grep libpostal does return the library. Figured out it was due to pkg-config. It does not find the libpostal.pc file. Doing export PKG_CONFIG_PATH=/usr/lib/pkgconfig before running ./gradlew assemble did the trick.

**Comment by thatdatabaseguy** [comment]
Which OS is this?

**Comment by edi-bice** [comment]
Red Hat Enterprise Linux 6

**Comment by thatdatabaseguy** [comment]
Ok, tests for all of the libpostal bindings are on Mac and Ubuntu. Added a note to the README.
