### ISSUE TITLE
Build jpostal error on Mac OS

### ISSUE THREAD

**Issue by coachwei** [openvenues/jpostal#14]
I followed instructions to build postal and jpostal on MacOS per https://github.com/openvenues/jpostal. Everything worked fine until running:  

`./gradlew assemble`

Which resulted in the following error. How to resolve this? See below. Thank you. 

.......
```
checking if javac works... yes
checking for javac... /usr/bin/javac
checking symlink for /usr/bin/javac... /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/javac
checking for /System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers/jni.h... no
checking for /System/Library/Frameworks/JavaVM.framework/Versions/include/jni.h... no
configure: error: cannot find JDK header files
make: *** No rule to make target `install'.  Stop.
:buildJniLib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildJniLib'.
> Process 'command './build.sh'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 17.889 secs
```

**Comment by thatdatabaseguy** [comment]
These are the relevant lines:

```
checking for /System/Library/Frameworks/JavaVM.framework/Versions/include/jni.h... no
configure: error: cannot find JDK header files
```

You'll need to find jni.h on your system and make sure it's on the C include path.

**Comment by coachwei** [comment]
It turns out that the build process is looking for the header file jni.h at /System/Library/Frameworks/JavaVM.framework/Versions/include/ directory, which doesn't exist on MacOS (Sierra). The JDK installation has these files at /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/include/. 

Is there a way to tell the build process to look for the header files in a different location?

**Comment by thatdatabaseguy** [comment]
From [configure.ac](https://github.com/openvenues/jpostal/blob/master/configure.ac#L19), you can set JNI_INCLUDE_DIRS and they'll be added to the C include flags.

I wrote libpostal and all its bindings on a Mac (still on El Capitan though), and this shouldn't be necessary if Java/JNI is installed through XCode (Apple Developer Tools).

**Comment by coachwei** [comment]
thanks @thatdatabaseguy !  Unfortunately Java/JNI wasn't installed through XCode for me...

I did set JNI_INCLUDE_DIRS to the right directory that contains `jni.h` in `configure.ac`.  When i ran 
`./gradlew assemble`

I saw the same error (can't find the jni.h). Do i need to run some other scripts for it to kick in?

(I did try to run `autoconf`, which generated an updated `configure` file that I can see with my updates to JNI_INCLUDE_DIRS. But still got the same error when running `./gradlew assemble`)

**Comment by thatdatabaseguy** [comment]
JNI_INCLUDE_DIRS is an environment variable, no need to modify configure.ac, just:

```shell
export JNI_INCLUDE_DIRS=/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/include/
./gradlew assemble
```

If that doesn't work, I'd say overall this doesn't seem to be libpostal-related, and it's a non-standard install of Java, so Google is probably the best resource.

**Comment by coachwei** [comment]
Tried setting the variable JNI_INCLUDE_DIRS, and didn't work. Same error as before. 

Don't think it is related to non-standard installation of Java. In newer version of Mac, the JDK documentation (including the .h files) was left out. For example, see:

`http://stackoverflow.com/questions/9704376/how-to-install-java-native-development-headers-on-os-x-lion`

Whenever you need to build JNI, you need to manually specify the jni.h file locations, see documentation from Apple website:

`https://developer.apple.com/library/content/documentation/Java/Conceptual/Java14Development/05-CoreJavaAPIs/CoreJavaAPIs.html`

(My java installation was fairly typical. When I ran into the jni.h issue, i went to Oracle.com, downloaded and installed JDK from there to see if it fixed the problem. It didn't). 

My suspicion is that the JNI_INCLUDE_DIRS variables are not being passed to gcc compiler for some reason. Is there a place that we can add the jni.h path to gcc compiler directly?

**Comment by thatdatabaseguy** [comment]
Normally you would have to specify the JNI include dir, but we use an autoconf macro that's supposed to checks most common locations for you. I just upgraded the macro to the latest version from GNU, so try pulling from master and seeing if that fixes it.

**Comment by coachwei** [comment]
@thatdatabaseguy the upgrade DID the magic. the error went away. I didn't even have to bother with setting JNI_INCLUDE_DIRS variable. 

However, towards the later part of the build process (install), i got the following error:

`make[2]: Nothing to be done for `install-data-am'.
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
:compileJava
cache taskArtifacts.bin (/Volumes/Data/MyProjects/xcode/jlibpostal/.gradle/2.9/taskArtifacts/taskArtifacts.bin) is corrupt. Discarding.

FAILURE: Build failed with an exception.

* What went wrong:
Could not open cache taskArtifacts.bin (/Volumes/Data/MyProjects/xcode/jlibpostal/.gradle/2.9/taskArtifacts/taskArtifacts.bin).
> Corrupted FreeListBlock 0 found in cache '/Volumes/Data/MyProjects/xcode/jlibpostal/.gradle/2.9/taskArtifacts/taskArtifacts.bin'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 20.01 secs`

I have no idea what this problem is... what to do from here?

**Comment by thatdatabaseguy** [comment]
Hm, can you ```rm -rf``` the entire jpostal checkout, clone it and build again?

**Comment by coachwei** [comment]
did that. Removed the entire repo, recloned it and do the build. Got the same error. 

```
* What went wrong:
Could not open cache taskArtifacts.bin (/Volumes/Data/MyProjects/xcode/jlibpostal/.gradle/2.9/taskArtifacts/taskArtifacts.bin).
> Corrupted FreeListBlock 0 found in cache '/Volumes/Data/MyProjects/xcode/jlibpostal/.gradle/2.9/taskArtifacts/taskArtifacts.bin'.

```

**Comment by thatdatabaseguy** [comment]
It seems like there's some cache directory that needs to be removed as well. What is "jlibpostal"? This project is called jpostal, so assuming that's some other project for which this is a dependency, maybe that project needs a ```gradle clean``` or something along those lines.

In any case, this seems to be solidly in Gradle territory now, and since I can't see your machine, it's better if you Google the problem and post what you find.

**Comment by coachwei** [comment]
I rebooted my machine and the cache issue went away.  So now my build is successful! 
Thanks @thatdatabaseguy.

**Comment by taoj** [comment]
Hi, @albarrentine I tried to build jpostal and found the same issue in this thread. I pull from the master also tried `export JNI_INCLUDE_DIRS`, still seeing the `configure: error: cannot find JDK header files` error. Any suggestions? Thanks a lot!
