### ISSUE TITLE
Create a tag of the latest commit as 1.0 release?

### ISSUE THREAD

**Issue by mateor** [openvenues/jpostal#24]
Hi, thanks for all the work you do on libpostal and the various language bindings! We are excited to use them to improve our data quality.

I am using RPM to package and distribute libpostal and jpostal to our fleet. Our RPM builder bootstraps source code packages, [preferably from the Releases tab of the upstream Github project](https://github.com/openvenues/jpostal/releases).

I see that you have tagged [a pypostal as 1.0](https://github.com/openvenues/pypostal/commit/ee27201333beaeb0e14be567c79bad64c12a9676), which [has an analog in jpostal](0364c0d35694d2c6800805e2adc2b9122aa5d207).

Would it be possible for you to tag the latest jpostal commit so that Github packages it up as tarball and zip packages?

**Comment by thatdatabaseguy** [comment]
@mateor no problem, done! I knew Foursquare was adding libpostal to its venue pipeline, but exciting to see it's getting deployed.

Once the new models are trained, I'll be releasing a 1.1 for libpostal which contains a number of parser improvements based on our Github issues. It'll also expose a few new functions related to near-duplicate detection in venues (probably relevant to folks there). Keep an eye out for that release. Will probably implement the changes in jpostal and bump the version on this binding as well.

**Comment by mateor** [comment]
Wow, thanks a million! I will be able to consume directly from your repo, a very strong preference :)

As mentioned, we are deploying libpostal and the shared object files as RPMs. Let me know if you would like me to make the spec files available publicly. The RPMs may end up a bit coupled to our infrastructure but possibly people could get use from seeing an example configuration.

**Comment by thatdatabaseguy** [comment]
That would be great, would love to publish some official packages at some point.
