### ISSUE TITLE
Can't build jpostal

### ISSUE THREAD

**Issue by ChrisiR123** [openvenues/jpostal#27]
Hi,
I followed your installation instruction (using Ubuntu 16.04) until "./gradlew assemble".
I installed gradle 4.3.1 and after executing "sudo ldconfig" I ran the command "gradle wrapper". When I try now to run "./gradlew assemble" then i get a build exception:

"FAILURE: Build failed with an exception.

* What went wrong:
Task 'assemble' not found in root project 'libpostal'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED"

Thanks for your help!

**Comment by albarrentine** [comment]
Hm, that sounds like you're running `./gradlew assemble` inside the libpostal (C) project, not the jpostal (Java) project. If you downloaded the libpostal C project into another directory, you'll have to `cd` back to the jpostal project and build from there.

**Comment by ChrisiR123** [comment]
Oh, my bad.
Thank you, it works now!! =)
