### ISSUE TITLE
jpostal_expander not present

### ISSUE THREAD

**Issue by janvidpa** [openvenues/jpostal#3]
Hi,

When I say AddressExpander.getInstance(); I get the following exception
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jpostal_expander in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at com.mapzen.jpostal.AddressExpander.<clinit>(AddressExpander.java:7)
	at addresscleanup.AddressCleanup.main(AddressCleanup.java:21)

It seems jpostal_expander is not present at all in src/main/jniLibs. Do I need to explicitly set the java library path to another location?

**Comment by thatdatabaseguy** [comment]
Yes, jpostal builds shared object files (.so on Linux, .jniLib on Mac) that need to be on java.library.path (after you run ```gradle assemble``` the .so files can be found in build/natives in your checkout dir. For running the tests, we set this explicitly [here](https://github.com/openvenues/jpostal/blob/master/build.gradle#L18).

If you use gradle, there's a plugin called gradle-natives that may be helpful: https://github.com/cjstehno/coffeaelectronica/wiki/Going-Native-with-Gradle

**Comment by janvidpa** [comment]
Got it. Thanks!

**Comment by reemak** [comment]
![image](https://user-images.githubusercontent.com/7968031/71850384-04f46600-3089-11ea-90cb-952c9af0ffb8.png)


Get this error on import 
Spark cluster is on HDInsight on Azure and using Zeppelin notebook for code.
Can someone tell me how to fix it
